config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  root :to => 'site#index'
  
  get "about" => "site#about"
  get "equipment" => "site#equipment"
  get "feedback" => "site#feedback"
  get "contact" => "site#contact"

  get "news" => "site#news"
  get "news/:id" => "site#news_body"
  get "news/category/:id" => "site#news_category"
  get "news/category/news/:id" => "site#product_body"

  get "products" => "site#products"
  get "product/:id" => "site#product_body"
  get "products/category/:id" => "site#product_category"
  get "products/category/product/:id" => "site#product_body"

  post "send_feedback" => "site#send_feedback"

  get "jobs" => "site#jobs"
  get "jobs/:id" => "site#job_body"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
        can :manage, :all
    else
        can :read, :all
    end

    alias_action :create, :read, :update, :to => :cru

    if user.has_role? :publisher
        can :cru, News
    end

    can [:read, :update], AdminUser, :id => user.id

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # def roles= ids
  #   global_roles = Role.global
  #   global_ids = global_roles.collect { |r| r.id }

  #   exists_ids = self.roles.collect { |r| r.id }

  #   exists_ids.each do | id |
  #       name = Role.find(id).name
  #       unless ids.include? exists_ids
  #           self.remove_role name
  #       end
  #   end

  #   ids.each do |id|
  #       name = Role.find(id).name
  #       if global_ids.include? id
  #           self.add_role name
  #       end
  #   end
  # end
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :image, ImageUploader
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/label.rb
class Label < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
    has_many :sort_news
    has_many :categories, :through => :sort_news, :source => :news_category
    
    resourcify
    accepts_nested_attributes_for :categories

    after_initialize :assign_defaults_on_new, if: 'new_record?'

    private
    def assign_defaults_on_new
        self.pubdate = DateTime.now
    end
end

app/models/news_category.rb
class NewsCategory < ActiveRecord::Base
    has_many :sort_news
    has_many :news, through: :sort_news

    has_many :sub_categories, class_name: "NewsCategory", foreign_key: "news_category_id"
    belongs_to :parent, class_name: "NewsCategory", foreign_key: "news_category_id"
end

app/models/prod_category.rb
class ProdCategory < ActiveRecord::Base
    has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category, 
             :class_name => "ProdCategory", 
             :foreign_key => "prod_category_id"
end

app/models/role.rb
class Role < ActiveRecord::Base
  resourcify

  has_and_belongs_to_many :admin_users, :join_table => :admin_users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true
end

app/models/sort_news.rb
class SortNews < ActiveRecord::Base
  belongs_to :news
  belongs_to :news_category
end

app/controllers/jobs_controller.rb
class JobsController < InheritedResources::Base

  private

    def job_params
      params.require(:job).permit(:position, :work_loc, :requirements, :description, :expired_date)
    end
end

app/controllers/labels_controller.rb
class LabelsController < InheritedResources::Base

  private

    def label_params
      params.require(:label).permit(:name, :content)
    end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  private

    def product_params
      params.require(:product).permit(:name, :show_in_home, :pic, :prod_categories_id, :description)
    end
end

app/controllers/site_controller.rb
# encoding: utf-8
class SiteController < InheritedResources::Base
    def index
        @products = Product.where(:show_in_home => true).order(id: :desc)
    end

    def equipment
        @equipments = Equipment.all.order(id: :desc)
    end

    def news
        @news = News.all.order(pubdate: :desc)
    end

    def news_body
        @news = News.find(params[:id])
    end

    def news_category
        @news = NewsCategory.find(params[:id]).news.order(id: :desc)
        render :news
    end

    def products
        @products = Product.all.order(id: :desc)
    end

    def product_body
        @product = Product.find(params[:id])
    end

    def product_category
        @products = ProdCategory.find(params[:id]).products.order(id: :desc)
        render :products
    end

    def jobs
        @jobs = Job.where("expired_date > ?", DateTime.now).order(id: :desc)
    end

    def job_body
        @job = Job.find(params[:id])
    end

    def send_feedback
        company = params[:company]
        address = params[:address]
        visitor = params[:username]
        tel = params[:tel]
        fax = params[:fax]
        productName = params[:product]
        desc = params[:product_desc]
        advice = params[:advice]
        subject = "jingshunfood.com在线反馈：来自#{company}的#{visitor}留言"
        from = params[:email]
        to = label("在线反馈接收邮箱")
        mail_content = <<EOF
访客：#{visitor}
======================
公司名：  #{company}
公司地址：#{address}
电话：    #{tel}
传真：    #{fax}

=======================
关注产品：#{productName}
详细说明：#{desc}

========================
其他意见：#{advice} 
EOF

        msg = <<END_OF_MESSAGE
From: #{visitor} <#{from}>
To: <#{to}>
Subject: #{subject}

#{mail_content}
END_OF_MESSAGE

        begin
            _send_email(msg, from, to)
            flash[:message] = "您的反馈已经发送成功，感谢您的关注!"
            render :feedback
        rescue Exception => error  
            puts error
            flash[:message] = "反馈发送失败！"
            render :feedback
        end
    end


    private 
    def _send_email(msg, from, to)
        require "net/smtp"
        to = if to.nil?
        server = label("SMTP服务器")
        smtp = Net::SMTP.start(
            server, 
            label("SMTP端口").to_i, 
            server, 
            label("发送邮件账号"), 
            label("发送邮件密码"))
        smtp.send_message msg, from, to
        smtp.finish
    end

    def label(name)
        lb = Label.where(name: name).first
        if lb
            content
        else
            ""
        end
    end
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def content name
        rec = Label.where(:name => name).first
        return rec ? raw(rec.content) : ""
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/prod_categories_helper.rb
module ProdCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :work_loc %><br>
    <%= f.text_field :work_loc %>
  </div>
  <div class="field">
    <%= f.label :requirements %><br>
    <%= f.text_area :requirements %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :expired_date %><br>
    <%= f.date_select :expired_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Work loc</th>
      <th>Requirements</th>
      <th>Description</th>
      <th>Expired date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.position %></td>
        <td><%= job.work_loc %></td>
        <td><%= job.requirements %></td>
        <td><%= job.description %></td>
        <td><%= job.expired_date %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Work loc:</strong>
  <%= @job.work_loc %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @job.requirements %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Expired date:</strong>
  <%= @job.expired_date %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/labels/_form.html.erb
<%= form_for(@label) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Labels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= label.content %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form' %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @label.content %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>